version: '2'
services:
    php:
        build: ./docker/php7
        ports:
            - "8080:80"
        volumes:
            - ./src:/var/www/html
        links:
            - db-mysql
    db-mysql:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
          - ./docker/data/mysql:/var/lib/mysql
